CUA/urls.py
from django.urls import path
from CUA.views import register, registerCustomer, registerDeveloper, userLogin, dashboard, customerDash, developerDash
from django.conf.urls.static import static
from django.conf import settings

app_name = 'CUA'

urlpatterns = [
    path('register/', register, name='register'),
    path('registerCustomer/', registerCustomer, name='registerCustomer'),
    path('registerDeveloper/', registerDeveloper, name='registerDeveloper'),
    path('login/', userLogin, name='userLogin'),
    path('dashboard/', dashboard, name='dashboard'),
    path('customerDash/', customerDash, name='customerDash'),
    path('developerDash/', developerDash, name='developerDash'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DME/urls.py
from django.contrib import admin
from django.urls import include, path
from Home.views import index_view
from CUA.views import dashboard, customerDash, developerDash, userLogout
from django.conf.urls.static import static
from django.conf import settings

from CUA.views import register
#from Service.views import reportServices_views


urlpatterns = [

    path('', index_view, name='index_view'),
    path('admin/', admin.site.urls),

    path('Contact/', include('Contact.urls')),
    path('Product/', include('Product.urls')),
    path('About/', include('About.urls')),
    path('Payments/', include('Payments.urls')),
    path('Home/', include('Home.urls')),
    path('blog/', include('blog.urls')),
    path('CUA/', include('CUA.urls')),
    path('logout/', userLogout,name='userLogout'),
    path('dashboard/', dashboard, name='dashboard'),
    path('customerDash/', customerDash, name='customerDash'),
    path('developerDash/', developerDash, name='developerDash'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CUA/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Customer(models.Model):
    customer = models.OneToOneField(User,on_delete=models.CASCADE)
    idno = models.IntegerField(blank=False)
    branch = models.CharField(max_length=256, blank=False)
    is_customer = models.BooleanField(default=True)

    def __str__(self):
        return self.customer.username

class Developer(models.Model):
    developer = models.OneToOneField(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=256, blank=False)
    phone = models.IntegerField()
    is_customer = models.BooleanField(default=False)

    def __str__(self):
        return self.developer.username

CUA/forms.py
from django import forms
from django.contrib.auth.models import User
from CUA.models import Customer, Developer


class customerForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password']


BRANCH_CHOICES = (
    ('COMPS', 'COMPS'),
    ('IT', 'IT'),
    ('EXTC', 'EXTC')
)


class customerAddForm(forms.ModelForm):
    branch = forms.CharField(widget=forms.Select(choices=BRANCH_CHOICES))

    class Meta():
        model = Customer
        fields = ['idno', 'branch']


class developerForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password']


SUBJECT_CHOICES = (
    ('DS', 'Data Structures'),
    ('DLD', 'Digital Logic Design'),
    ('DM', 'Discrete Mathematics'),
    ('LA', 'Linear Algebra')
)


class developerAddForm(forms.ModelForm):
    subject = forms.CharField(widget=forms.Select(choices=SUBJECT_CHOICES))

    class Meta():
        model = Developer
        fields = ['subject', 'phone']

CUA/views.py
from django.shortcuts import render, redirect
from CUA.forms import customerForm, customerAddForm, developerForm, developerAddForm
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from CUA.models import Customer, Developer
from django.contrib.auth.models import User


# Create your views here.

def index_views(request):
    return render(request, 'Home/home.html')


@login_required
def userLogout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index_view'))


def register(request):
    return render(request, 'CUA/register.html')


def registerCustomer(request):
    registered = False
    if request.method == 'POST':
        var_customerForm = customerForm(request.POST)
        var_customerAddForm = customerAddForm(request.POST)
        if var_customerForm.is_valid() and var_customerAddForm.is_valid():
            customerprimary = var_customerForm.save()
            customerprimary.set_password(customerprimary.password)
            customerprimary.save()
            customerAdd = var_customerAddForm.save(commit=False)
            customerAdd.customer = customerprimary
            customerAdd.save()
            registered = True
    else:
        var_customerForm = customerForm()
        var_customerAddForm = customerAddForm()
    return render(request, 'CUA/registerCustomer.html',
                  {'var_customerForm': var_customerForm, 'var_customerAddForm': var_customerAddForm,
                   'registered': registered})


def registerDeveloper(request):
    registered = False
    if request.method == 'POST':
        var_developerForm = developerForm(request.POST)
        var_developerAddForm = developerAddForm(request.POST)
        if var_developerForm.is_valid() and var_developerAddForm.is_valid():
            developerprimary = var_developerForm.save()
            developerprimary.set_password(developerprimary.password)
            developerprimary.save()
            developerAdd = var_developerAddForm.save(commit=False)
            developerAdd.developer = developerprimary
            developerAdd.save()
            registered = True
    else:
        var_developerForm = developerForm()
        var_developerAddForm = developerAddForm()
    return render(request, 'CUA/registerDeveloper.html',
                  {'var_developerForm': var_developerForm, 'var_developerAddForm': var_developerAddForm,
                   'registered': registered})


def userLogin(request):
    invalidlogin = False
    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('dashboard'))
            else:
                return HttpResponse('Account not active')
        else:
            invalidlogin = True
            return redirect('/CUA/login/')

    else:

        return render(request, 'CUA/login.html', {'invalidlogin': invalidlogin})


@login_required
def dashboard(request):
    try:
        current = Customer.objects.get(customer=request.user)
    except Customer.DoesNotExist:
        current = Developer.objects.get(developer=request.user)
    if current.is_customer:
        return redirect('/customerDash/')
    else:
        return redirect('/developerDash/')
    return render(request, 'CUA/dashboard.html')


def customerDash(request):
    return render(request, 'CUA/customerDash.html')


def developerDash(request):
    return render(request, 'CUA/developerDash.html')

templates/CUA/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>myGrades</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'index_view' %}">Home</a>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation"></button>
    <div class="collapse navbar-collapse" id="collapsibleNavId">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'index_view' %}">Admin</a>
        </li>

        <li class="nav-item active">
          <a class="nav-link" href="{% url 'CUA:register' %}">Register</a>
        </li>
        {% if user.is_authenticated %}
    


        <li class="nav-item active">
          <a class="nav-link" href="{% url 'CUA:dashboard' %}">Dashboard</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'userLogout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'CUA:userLogin' %}">Login</a>
        </li>
        {% endif %}

      </ul>

    </div>
  </nav>
  <div class="container">
    {% block body_block %}
    {% endblock %}
  </div>
</body>

</html>

templates/CUA/customerDash.html
{% extends 'base_dashcustomer.html' %}
{% block body_block %}

<div class="container pt-3 ">
    <div class="jumbotron w-75">
        <h2>Customer Dash</h2>
        <div class="d-flex" id="wrapper">

            <!-- Page content wrapper-->
            <div id="page-content-wrapper">

                <!-- Page content-->
                <div class="container-fluid">
                    <h1 class="mt-4">Simple Sidebar</h1>
                    <p>The starting state of the menu will appear collapsed on smaller screens, and will appear non-collapsed on larger screens. When toggled using the button below, the menu will change.</p>
                    <p>
                        Make sure to keep all page content within the
                        <code>#page-content-wrapper</code>
                        . The top navbar is optional, and just for demonstration. Just create an element with the
                        <code>#sidebarToggle</code>
                        ID which will toggle the menu when clicked.
                    </p>
                </div>
            </div>
        </div>
        <hr>
    </div>
</div>


{% endblock %}

templates/CUA/dashboard.html
{% extends 'base.html' %}
{% block body_block %}
{% endblock %}

templates/CUA/developerDash.html
{% extends 'base_dashdeveloper.html' %}
{% block body_block %}
 {% load static %}
<div class="container pt-3">
    <div class="jumbotron w-75">
        <h2>Developer Dash</h2>
        <div class="d-flex" id="wrapper">

            <!-- Page content wrapper-->
            <div id="page-content-wrapper">

                <!-- Page content-->
                <div class="container-fluid">
                    <h1 class="mt-4">Simple Sidebar</h1>
                    <p>The starting state of the menu will appear collapsed on smaller screens, and will appear non-collapsed on larger screens. When toggled using the button below, the menu will change.</p>
                    <p>
                        Make sure to keep all page content within the
                        <code>#page-content-wrapper</code>
                        . The top navbar is optional, and just for demonstration. Just create an element with the
                        <code>#sidebarToggle</code>
                        ID which will toggle the menu when clicked.
                    </p>
                </div>
            </div>
        </div>

        <hr>
    </div>
</div>

{% endblock %}

templates/CUA/login.html
{% extends "CUA/base.html" %}
{% block body_block %}
<div class="container pt-3">
  <div class="jumbotron w-75 pt-3">
    {% if invalidlogin %}
    <h3>Please enter correct login details!</h3>
    {% endif %}
    <form action="{% url 'CUA:userLogin' %}" method="POST">
      {% csrf_token %}
      <label for="username">Username: </label>
      <input type="text" name="username" placeholder="Enter Username">
      <label for="password">Password: </label>
      <input type="password" name="password" placeholder="Enter Password">
      <input type="Submit" value="Login">
    </form>
  </div>
</div>

{% endblock %}

templates/CUA/register.html
{% extends 'CUA/base.html' %}
{% block body_block %}

<div class="container pt-3 ">
  <div class="jumbotron w-75">
    <h1 class="display-3">Register Here!</h1>

    <hr class="my-2">
    <p class="lead">
      <a class="btn btn-primary btn-lg" href="{% url "CUA:registerCustomer" %}" role="button">I'm a Customer</a>
      <a class="btn btn-primary btn-lg" href="{% url "CUA:registerDeveloper" %}" role="button">I'm a Developer</a>
    </p>
  </div>

</div>
{% endblock %}

templates/CUA/registerCustomer.html
{% extends 'base_registercustomer.html' %}
{% block body_block %}

<div class="jumbotron pt-3 w-75">
   {% if registered %}
        <h1>Thanks for registering, Please Log in!</h1>
    {% else %}
        <h1>Registration for Customers:</h1>
        <form action="" method="POST">
            {% csrf_token %}
            {{ var_customerForm.as_p }}
            {{ var_customerAddForm.as_p }}
            <input type="submit" value="Register" class="btn btn-primary">
        </form>
    {% endif %}
</div>


{% endblock %}

templates/CUA/registerDeveloper.html
{% extends 'base_registerdeveloper.html' %}
{% block body_block %}

<div class="jumbotron pt-3 w-75">
   {% if registered %}
        <h1>Thanks for registering, Please Log in!</h1>
    {% else %}
        <h1>Registration for Developers:</h1>
        <form action="" method="POST">
            {% csrf_token %}
            {{ var_developerForm.as_p }}
            {{ var_developerAddForm.as_p }}
            <input type="submit" value="Register" class="btn btn-primary">
        </form>
    {% endif %}
</div>


{% endblock %}